export const UPDATE_PRODUCTS_IN_REVIEW = 'UPDATE_PRODUCTS_IN_REVIEW';

export const ADD_PRODUCT_IN_REVIEW = 'ADD_PRODUCT_IN_REVIEW';

export const ADD_TO_NEW_DONATIONS = 'ADD_TO_NEW_DONATIONS';

export const CLEAR_NEW_DONATIONS = 'CLEAR_NEW_DONATIONS';
